version: "3"

services:
  poetium_backend:
    build: .
    environment:
      - MONGO_DB_HOST=poetium_db
      - APP_SECRET=secretfghjkl
      - DATABASE_NAME=node_blog
    ports:
    - "3000:3000"
    depends_on:
      - poetium_db
  poetium_db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: node_blog
    restart: always
    ports:
    - "27017:27017"
    volumes:
      - ./database:/data/db
      - ./mongo-seed:/mongo-seed
      - ./mongo_init.sh:/docker-entrypoint-initdb.d/mongo_init.sh:rw
